### ISSUE TITLE
Extracting Image Features

### ISSUE THREAD

**Issue by feiyuchen7** [facebookresearch/corefnmn#3]
Hi I still don't get how to extract image features, do we need to download COCO? And what next?

**Comment by satwikkottur** [comment]
Hello @feiyuchen7,

To extract features, please following the README.md [here](https://github.com/ronghanghu/n2nmn#download-and-preprocess-the-data-1).

Specifically, it says the following:

> Download the COCO images from http://mscoco.org/, extract features from the images, and store them under `exp_vqa/data/resnet_res5c/`. In our experiments, we resize all the COCO images to 448 x 448, and use the *res5c* layer output of shape (1, 14, 14, 2048) from the [ResNet-152](https://github.com/KaimingHe/deep-residual-networks) network pretrained on ImageNET classification (feature stored as numpy array in HxWxC format). **In our experiments, we use the same ResNet-152 res5c features as in [MCB](https://github.com/akirafukui/vqa-mcb), except that the extracted features are stored in NHWC format (instead of NCHW format used in MCB).** 

Hope this helps!
