### ISSUE TITLE
How long it takes to train and number of parameters

### ISSUE THREAD

**Issue by idansc** [facebookresearch/corefnmn#4]
Hey, thanks for this great git. 
Can you roughly state how long it takes to train the model, and how many parameters it has?

Thanks in advance

**Comment by satwikkottur** [comment]
Hello @idansc,

The discriminative model with `lstm_size` of `1000` has around 102M parameters while that with `lstm_size` of `500` has about 38M parameters. Time to train the model depends heavily on the I/O speed and GPU configuration. On a Titan Xp, it takes about ~30-36 hours.
