### ISSUE TITLE
When to release visualization scripts

### ISSUE THREAD

**Issue by YuCosine** [facebookresearch/corefnmn#6]
Hi,
Thanks for your code. I am trying to reproduce the results in the ECCV paper. The training and eval code goes well and they are easy to follow.

A trivial bug in line 91 of exp_vd/eval_sl.py:
```
if args['use_refer']:
  # use refer module
  file_name = 'imdb/imdb_%s_refermrf_att.npy' % args['test_split']
else:
  file_name = 'imdb/imdb_%s.npy' % args['test_split']
```
'use_refer' is set as default but imdb_val_refermrf_att.npy is not created in the preprocessing by default. I link it directly with imdb_val.py and it seems to work well.

I also hope to try visualization but it is not ready yet. Do you have a time schedule for releasing the visualization scripts?

**Comment by satwikkottur** [comment]
Thanks for bringing this up. I'll take a look and get back to you by the end of the week.

For the visualizations, please do take a look at `vis/visualize_dialogs.py` and `exp_vd/visualize_sl.py` to get an idea of how to run the visualization code. It is currently not streamlined and `exp_vd/visualize_sl.py` needs work to accommodate the change in code styles (camel case to underscores). I currently don't have a schedule for releasing the visualization scripts but will try to get them out as soon as I can, thanks!
